### ISSUE TITLE
Do not have to change asset url scheme???

### ISSUE THREAD

**Issue by anhtriuahihi** [Axinom/drm-quick-start-ios#3]
I saw many sample they all have to change m3u8 url scheme so that resourceLoader delegate can work but i don't see it in your code, i don't have cert url so i can not run your code for seeing what happen. Can you explain?

**Comment by Heronyme** [comment]
Hello!

Do you mean the scheme in the URI attribute of the EXT-X-KEY tag in the m3u8 playlist? In case of FairPlay, main requirement is that it should start with "skd://", followed by any custom string that identifies the asset/key (exact is decided by the FairPlay implementer).

For example, in the case of Axinom DRM, the included sample media contains the following EXT-X-KEY tag, where the URI can contain both the Key ID and IV to use for decryption:
```
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://9E86D6E6-DA0E-4606-9D0D-719F2641A949:337C796906D0EBDDDDC9550A55C92722",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
```

If the "skd://" is present in the manifest, then this media can be loaded using the FairPlay workflow. And then in player code you can get the "skd" URI, and parse it as needed to get the data needed for generating the desired key request.

In the player code, this occurs here: "shouldWaitForLoadingOfRequestedResource".

If you do not have a FairPlay certificate, but wish to try out FairPlay workflows using our services, please sign up for a Axinom DRM Evaluation Account: https://drm.axinom.com/evaluation-account/

**Comment by anhtriuahihi** [comment]
Thank for your explain.
I refer this [https://stackoverflow.com/questions/26649865/avassetresourceloaderdelegate-methods-not-working-on-device](url) and they all recommend change "http" or "https" to something else.
But you didn't and it still working fine?

**Comment by Heronyme** [comment]
Yes, current code is working nicely, and we specify the playlists using simple http:// or https:// schemes. Perhaps there's some difference in your use case or something else. Unfortunately, I don't think we can help you much more at the moment as this app is mostly about trying out playback of FairPlay protected HLS content with using Axinom DRM.
